# Generated by Django 4.2 on 2025-08-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
