# Generated by Django 4.2 on 2025-08-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0007_remove_employee_joining_date_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
