# Generated by Django 4.2 on 2025-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0010_remove_employee_email_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
