# Generated by Django 4.2 on 2025-08-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0011_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
    ]
