# Generated by Django 4.2 on 2025-08-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0012_remove_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
