# Generated by Django 4.2 on 2025-08-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0015_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='raw_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
