# Generated by Django 4.2 on 2025-09-02 15:05

import Attendanceapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0019_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=Attendanceapp.models.default_date),
        ),
        migrations.AlterField(
            model_name='permission',
            name='date',
            field=models.DateField(default=Attendanceapp.models.default_date),
        ),
    ]
