# Generated by Django 5.2.11 on 2026-02-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendanceapp', '0021_leavetype_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={},
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendanceapp.employee'),
        ),
    ]
